// <auto-generated />
namespace application_facture.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class montantsting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(montantsting));
        
        string IMigrationMetadata.Id
        {
            get { return "202403300901515_montantsting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
